import { Movie } from "../models/movie.model";

export const MOVIES: Movie[] = [
  {
    id: 0,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
  {
    id: 1,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
  {
    id: 2,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
  {
    id: 3,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
  {
    id: 4,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
  {
    id: 5,
    title: "Марсианин,",
    originalTitle: "The Martian 2015",
    category: "Фантастика, приключения",
    rating: 7.8,
    image: "./img/movie.png",
    link: "./movie.html",
  },
]